---
title: "preciseTAD: a machine-learning framework for predicting boundaries of 3D genomic elements"
author:
- name: Spiro Stilianoudakis
  affiliation:
  - &1 Department of Biostatistics, Virginia Commonwealth University, Richmond, VA
- name: Mikhail Dozmorov
  affiliation:
  - *1
date: '`r format(Sys.Date(), "%B %e, %Y")`'
output:
  rmarkdown::html_document:
    highlight: pygments
    toc: true
    toc_depth: 3
    fig_width: 5
bibliography: bibliography.bib
vignette: >
  %\VignetteIndexEntry{preciseTAD: a machine-learning framework for predicting boundaries of 3D genomic elements}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
# Set up the environment
knitr::opts_chunk$set(echo=T, warnings=F, message=F,
  collapse = TRUE,
  comment = "#>"
)
set.seed(1)
options(stringsAsFactors = FALSE)
```

## Installation

```{r}
# if (!requireNamespace("BiocManager", quietly=TRUE))
#     install.packages("BiocManager")
# BiocManager::install("preciseTAD")
library(preciseTAD)
```

## Obtaining ground truth TAD boundaries

## Obtaining functional genomic elements

## Implementing *preciseTAD* functionality

### Model building

### Optimization

### Boundary prediction with *preciseTAD*

### Using *preciseTAD* with Juicebox

### Cross-cell-type prediction

## References